### ISSUE TITLE
Cannot define width and height of Frame when populated with widgets

### ISSUE THREAD

**Issue by yl642** [yl642/Tkinter_example#1]
https://github.com/yl642/Tkinter_example/blob/d0331a614fe7e1ff8ab7ae642a8d82e0ef7d01b6/gui_example.py#L121-L135

Hi Dr. Ward @dward2. I found adding widgets to Frame would override previous width/height setting, but even though I tried to set width/height to Frame object after adding widgets on it, it would still be the size that perfectly fitted the widgets within it.

**Comment by dward2** [comment]
The command `content.grid_propagate(False)` will turn off the grid manager that resizes a widget based on the child size.  The default is on (or True) in which case when objects (or children) are added to a widget, the widget resizes based on the size of the children.  

So, add the command above on line 127 of your code.

For more info, visit <https://effbot.org/tkinterbook/grid.htm#Tkinter.Grid.grid_propagate-method>

**Comment by yl642** [comment]
Thx!
